main: io.nicholaskhrangtong.ServerBot.Main
author: Asiatic
version: 1.0.0
name: ServerBot

commands:
   bye:
      decription: Usage /bye to get a link to a farewell picture.
   roll:
      description: Usage /roll <upper_bound> to get random number from 0 to your desired number.
   eightball:
      description: Usage /eightball <question> to get an answer from Magic 8ball.
   coin:
      description: Usage /coin to let chance decide your fate.
   spin:
      description: Usage /spin to see who the bottle lands on.
   snip:
      description: Usage /snip <toReplace> <replaceWith>.

permissions:
   serverbot.bye:
      description: Allows user to send a faremessage using </bye>.
      default: op
   server.roll:
      description: Allows user to roll for a number.
      default: op
   server.eightball:
      description: Allows user to access the wisdom from the eightball.
      default: op
   server.coin:
      description: Allows user to take a chance in life by letting a coin dictate the outcome.
   server.bottle:
      description: Allows user to spin the bottle.
   server.snip:
      description: Allows uer to edit chat messages.